# This file was generated by GoReleaser. DO NOT EDIT.
class Qiisync < Formula
  desc "Qiita CLI tool, support push and pull from/to local filesystem and Qiita."
  homepage "https://github.com/d-tsuji/qiisync"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/d-tsuji/qiisync/releases/download/v0.0.4/qiisync_0.0.4_darwin_amd64.zip"
    sha256 "8de02b6f71b599c8f9831e794d4486be749616b89515325329c08d1379eabe20"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/d-tsuji/qiisync/releases/download/v0.0.4/qiisync_0.0.4_linux_amd64.zip"
      sha256 "d5956bdba1b814a4315455fddac89f22d1d9c7086f26f836bfe7a689bec8ebcb"
    end
  end

  def install
    bin.install "qiisync"
  end

  test do
    system "#{bin}/qiisync"
  end
end
